const { GoogleGenAI } = require("@google/genai");
const fs = require("fs")

const Image = require("../Models/Image");
async function createRecord(req, res) {
    try {
        const { _id, userid, input } = req.body;

        if (!input) {
            return res.status(400).json({
                result: "Fail",
                reason: "Please Provide a Valid Prompt"
            });
        }

        const prompt = req.body.input;
        const ai = new GoogleGenAI({
            apiKey: process.env.GEMINI_API_KEY
        });
        const response = await ai.models.generateImages({
            model: "imagen-4.0-generate-001",
            prompt,
            config: {
                numberOfImages: 1,
                aspectRatio: req.body.dimension ?? "16:9",
                personGeneration: "allow_all",
            }
        });

        // Prepare folder
        const folderPath = path.join(__dirname, "../public/Generate/image");
        if (!fs.existsSync(folderPath)) {
            fs.mkdirSync(folderPath, { recursive: true });
        }

        let imageUrl = null;

        if (response.generatedImages && response.generatedImages.length > 0) {
            for (const generatedImage of response.generatedImages) {
                const buffer = Buffer.from(generatedImage.image.imageBytes, "base64");

                const fileName = `img_${Date.now()}.png`;
                const fullPath = path.join(folderPath, fileName);

                fs.writeFileSync(fullPath, buffer);
                imageUrl = `/Generate/image/${fileName}`;
            }
        } else {
            throw new Error("No image generated by Google Imagen API.");
        }

        // Save Response
        let data = new Image({
            user: req.body.userid,
            image: imageUrl
        })
        await data.save();

        res.send({ result: "Done", data: data });
    }
    catch (error) {
        console.log(error);

        res.status(500).send({
            result: "Fail",
            reason: "Internal Server Error"
        });
    }
}

async function getRecord(req, res) {
    try {
        const data = await Image.find({ user: req.params.userid }).sort({
            createdAt: -1
        });

        res.json({
            result: "Done",
            data
        });
    }
    catch (error) {
        console.log(error);

        res.status(500).json({
            result: "Fail",
            reason: "Internal Server Error"
        });
    }
}

async function getSingleRecord(req, res) {
    try {
        const data = await Image.findById(req.params._id);

        if (!data) {
            return res.status(404).json({
                result: "Fail",
                reason: "Chat not found"
            });
        }

        res.json({
            result: "Done",
            data
        });
    }
    catch (error) {
        console.log(error);

        res.status(500).json({
            result: "Fail",
            reason: "Internal Server Error"
        });
    }
}

async function deleteRecord(req, res) {
    try {
        const data = await Image.findById(req.params._id);
        if (data) {
            try {
                fs.unlinkSync(data.image)
            } catch (error) {

            }
            await data.deleteOne();
        }

        res.json({
            result: "Done"
        });
    }
    catch (error) {
        console.log(error);

        res.status(500).json({
            result: "Fail",
            reason: "Internal Server Error"
        });
    }
}

module.exports = {
    createRecord,
    getRecord,
    getSingleRecord,
    deleteRecord
};